"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var lastName = 'Santosh';
var newName = lastName.toUpperCase();
console.log(newName);
var age;
age = 25;
age = 25.5;
var dob = "25";
var result = parseInt(dob);
var isValid = false;
console.log("result: " + result);
var empList;
empList = ["Fouchimi", "Nvuh", "Ousmane"];
empList = empList.filter(function (name) { return name.length >= 5; });
console.log("empList", empList);
var numList;
numList = [1, 2, 3, 4, 5];
var res = numList.filter(function (num) { return num > 2; });
console.log(res);
